name: med_shield_new_version
description: MedShield Solutions Medical Insurance App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.8.0
  get: ^3.10.2
  shimmer: ^1.1.1
  flutter_screenutil: ^2.3.1
  polygon_clipper: ^1.0.2
  intl: ^0.16.1
  flutter_staggered_animations: ^0.1.2
  font_awesome_flutter: ^8.8.1
  octo_image: ^0.3.0
  cached_network_image: ^2.2.0+1
  popup_menu: ^1.0.5
  file_picker: ^1.13.3
  url_launcher: ^5.7.2
  geolocator: ^6.0.0+4
  device_preview: ^0.4.8
  dio: ^3.0.10
  hive: ^1.4.4+1
  firebase_messaging: ^7.0.3
  change_app_package_name: ^0.1.2
  hive_flutter: ^0.3.1
  flutter_downloader: ^1.5.1
  path_provider: ^1.6.21
  path: ^1.7.0
  easy_debounce: ^1.0.2
  bdaya_custom_splash:
    git:
      url: https://github.com/Bdaya-Dev/custom-splash.git
      ref: master
  med_shield_api:
    git:
      url: https://gitlab.com/bdaya-dev/alexesso/med-shield/med-shield-api.git
      ref: master
  easy_folder_picker: ^0.0.3
  lottie: ^0.7.0+1



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appIcon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.3
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Bold.ttf

    - family: AudioWide
      fonts:
        - asset: assets/fonts/Audiowide-Regular.ttf

flutter_intl:
  enabled: true
  class_name: S
  main_locale: ar

